name: Test working directory1

on:
  push:
    branches: 
      - master
    paths:
      - 'dir1/**'    

defaults:
    run: 
        working-directory: ./dir1 
  
jobs:
    job1:
        runs-on: ubuntu-16.04
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
        steps:
        - name: Check repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0  
            
        - name: Check commit status
          run: |
            # Check the status of the Git commit
            CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
            echo "Current status is: $CURRENT_STATUS"
            while [ "${CURRENT_STATUS^^}" = "PENDING" ]; 
              do sleep 10; 
              CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
            done;
            echo "Current status is: $CURRENT_STATUS"
            if [ "${CURRENT_STATUS^^}" = "FAILURE" ]; 
              then echo "Commit status failed. Canceling execution"; 
              exit 1; 
            fi 
        
        - name: dir1 directory
          run: cat README.md           
       
         