name: Test working directory

on:
  push:
    branches: 
      - master

defaults:
    run:
        working-directory: ./dir1      

jobs:
    job1:
        runs-on: ubuntu-16.04
                
        steps:
        
        - uses: actions/checkout@master
        - name: dir2 directory
          run: cat README.md           
        - name: dir1 directory
          run: |
            cat README.md
         