name: Test working directory1

on:
  push:
    branches: 
      - master
   
defaults:
    run: 
        working-directory: ./dir1 
  
jobs:
    job1:
        runs-on: ubuntu-16.04
                
        steps:
        
        - uses: actions/checkout@master
        - name: dir1 directory
          run: cat README.md           
       
         