name: Test working directory

on:
  push:
    branches: 
      - master

jobs:
    job1:
        runs-on: ubuntu-16.04
                
        steps:
        
        - uses: actions/checkout@master
        - name: dir2 directory
          run: cat README.md 
          working-directory: ./dir2
        - name: dir1 directory
          run: |
            cat README.md
          working-directory: ./dir1