name: Test working directory2

on:
  push:
    branches: 
      - master
    paths:
      - 'dir2/**'

defaults:
    run:
        working-directory: ./dir2 
  
jobs:
    job2:
        runs-on: ubuntu-16.04
                
        steps:
        
        - uses: actions/checkout@master
        - name: dir2 directory
          run: cat README.md   