name: Test working directory2

on:
  push:
    branches: 
      - master
    paths:
      - '!dir1/**'
  
jobs:
    job2:
        runs-on: ubuntu-16.04
                
        steps:
        
        - uses: actions/checkout@master
        - name: dir2 directory
          run: cat README.md   